
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  jmx:
    enabled: false
  datasource:
    jmx-enabled: false

server:
  port: 36015
  tomcat:
    uri-encoding: UTF-8

logging:
  config: classpath:logback.xml

endpoints:
  jmx:
    enabled: false