CREATE TABLE `user`(
  `id`   BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '名字',
  `age`  INT(3) NOT NULL DEFAULT 0 COMMENT '年龄',
  `password` VARBINARY(128) NOT NULL DEFAULT '' COMMENT '密码',
  PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT ='用户表';
