server:
  port: 6767


service:
  version:
    demo: 1.0.x

dubbo:
  application:
    name: annotation-consumer
    qosEnable: false
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer:
    timeout=3000